//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 16.0.32228.343
// 
namespace client.ServiceReference4 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(client.ServiceReference4.Cities))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(client.ServiceReference4.Sceduel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(client.ServiceReference4.PersonalMeeting))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(client.ServiceReference4.TypeAdvice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(client.ServiceReference4.Course))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(client.ServiceReference4.TypeCourse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(client.ServiceReference4.RegistrationForCourse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(client.ServiceReference4.CourseMeeting))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(client.ServiceReference4.Customers))]
    public partial class BaseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cities", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Cities : client.ServiceReference4.BaseEntity {
        
        private int codeField;
        
        private string nameCityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameCity {
            get {
                return this.nameCityField;
            }
            set {
                if ((object.ReferenceEquals(this.nameCityField, value) != true)) {
                    this.nameCityField = value;
                    this.RaisePropertyChanged("nameCity");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sceduel", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Sceduel : client.ServiceReference4.BaseEntity {
        
        private int codeField;
        
        private System.DateTime dateInMonthField;
        
        private System.DateTime timeInDayField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateInMonth {
            get {
                return this.dateInMonthField;
            }
            set {
                if ((this.dateInMonthField.Equals(value) != true)) {
                    this.dateInMonthField = value;
                    this.RaisePropertyChanged("dateInMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime timeInDay {
            get {
                return this.timeInDayField;
            }
            set {
                if ((this.timeInDayField.Equals(value) != true)) {
                    this.timeInDayField = value;
                    this.RaisePropertyChanged("timeInDay");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalMeeting", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class PersonalMeeting : client.ServiceReference4.BaseEntity {
        
        private double amountPaidField;
        
        private int codeField;
        
        private client.ServiceReference4.Customers customerField;
        
        private client.ServiceReference4.Sceduel ddayField;
        
        private string howToMeetField;
        
        private bool isPerformedField;
        
        private double lengthSessionInminutesField;
        
        private string paymentMethodField;
        
        private double priceField;
        
        private client.ServiceReference4.TypeAdvice typeAdviceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double amountPaid {
            get {
                return this.amountPaidField;
            }
            set {
                if ((this.amountPaidField.Equals(value) != true)) {
                    this.amountPaidField = value;
                    this.RaisePropertyChanged("amountPaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.ServiceReference4.Customers customer {
            get {
                return this.customerField;
            }
            set {
                if ((object.ReferenceEquals(this.customerField, value) != true)) {
                    this.customerField = value;
                    this.RaisePropertyChanged("customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.ServiceReference4.Sceduel dday {
            get {
                return this.ddayField;
            }
            set {
                if ((object.ReferenceEquals(this.ddayField, value) != true)) {
                    this.ddayField = value;
                    this.RaisePropertyChanged("dday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string howToMeet {
            get {
                return this.howToMeetField;
            }
            set {
                if ((object.ReferenceEquals(this.howToMeetField, value) != true)) {
                    this.howToMeetField = value;
                    this.RaisePropertyChanged("howToMeet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isPerformed {
            get {
                return this.isPerformedField;
            }
            set {
                if ((this.isPerformedField.Equals(value) != true)) {
                    this.isPerformedField = value;
                    this.RaisePropertyChanged("isPerformed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lengthSessionInminutes {
            get {
                return this.lengthSessionInminutesField;
            }
            set {
                if ((this.lengthSessionInminutesField.Equals(value) != true)) {
                    this.lengthSessionInminutesField = value;
                    this.RaisePropertyChanged("lengthSessionInminutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.paymentMethodField, value) != true)) {
                    this.paymentMethodField = value;
                    this.RaisePropertyChanged("paymentMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.ServiceReference4.TypeAdvice typeAdvice {
            get {
                return this.typeAdviceField;
            }
            set {
                if ((object.ReferenceEquals(this.typeAdviceField, value) != true)) {
                    this.typeAdviceField = value;
                    this.RaisePropertyChanged("typeAdvice");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeAdvice", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class TypeAdvice : client.ServiceReference4.BaseEntity {
        
        private int codeField;
        
        private string nameTypeAdviceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameTypeAdvice {
            get {
                return this.nameTypeAdviceField;
            }
            set {
                if ((object.ReferenceEquals(this.nameTypeAdviceField, value) != true)) {
                    this.nameTypeAdviceField = value;
                    this.RaisePropertyChanged("nameTypeAdvice");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Course : client.ServiceReference4.BaseEntity {
        
        private int codeField;
        
        private client.ServiceReference4.TypeCourse codeTypeCourseField;
        
        private string discribtionField;
        
        private int numberOfLessonsField;
        
        private double priceField;
        
        private string statusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.ServiceReference4.TypeCourse codeTypeCourse {
            get {
                return this.codeTypeCourseField;
            }
            set {
                if ((object.ReferenceEquals(this.codeTypeCourseField, value) != true)) {
                    this.codeTypeCourseField = value;
                    this.RaisePropertyChanged("codeTypeCourse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string discribtion {
            get {
                return this.discribtionField;
            }
            set {
                if ((object.ReferenceEquals(this.discribtionField, value) != true)) {
                    this.discribtionField = value;
                    this.RaisePropertyChanged("discribtion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numberOfLessons {
            get {
                return this.numberOfLessonsField;
            }
            set {
                if ((this.numberOfLessonsField.Equals(value) != true)) {
                    this.numberOfLessonsField = value;
                    this.RaisePropertyChanged("numberOfLessons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeCourse", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class TypeCourse : client.ServiceReference4.BaseEntity {
        
        private int codeField;
        
        private string nameTypeCourseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameTypeCourse {
            get {
                return this.nameTypeCourseField;
            }
            set {
                if ((object.ReferenceEquals(this.nameTypeCourseField, value) != true)) {
                    this.nameTypeCourseField = value;
                    this.RaisePropertyChanged("nameTypeCourse");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrationForCourse", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class RegistrationForCourse : client.ServiceReference4.BaseEntity {
        
        private int amountPaidField;
        
        private client.ServiceReference4.Course courseField;
        
        private client.ServiceReference4.Customers customerField;
        
        private string notesField;
        
        private string paymentMethodField;
        
        private int priceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int amountPaid {
            get {
                return this.amountPaidField;
            }
            set {
                if ((this.amountPaidField.Equals(value) != true)) {
                    this.amountPaidField = value;
                    this.RaisePropertyChanged("amountPaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.ServiceReference4.Course course {
            get {
                return this.courseField;
            }
            set {
                if ((object.ReferenceEquals(this.courseField, value) != true)) {
                    this.courseField = value;
                    this.RaisePropertyChanged("course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.ServiceReference4.Customers customer {
            get {
                return this.customerField;
            }
            set {
                if ((object.ReferenceEquals(this.customerField, value) != true)) {
                    this.customerField = value;
                    this.RaisePropertyChanged("customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                if ((object.ReferenceEquals(this.notesField, value) != true)) {
                    this.notesField = value;
                    this.RaisePropertyChanged("notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.paymentMethodField, value) != true)) {
                    this.paymentMethodField = value;
                    this.RaisePropertyChanged("paymentMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseMeeting", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class CourseMeeting : client.ServiceReference4.BaseEntity {
        
        private int codeField;
        
        private string contentMeetingField;
        
        private client.ServiceReference4.Course courseField;
        
        private client.ServiceReference4.Sceduel ddateField;
        
        private bool isPerformedField;
        
        private int lengthSessionInminutesField;
        
        private string notesField;
        
        private int serialField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contentMeeting {
            get {
                return this.contentMeetingField;
            }
            set {
                if ((object.ReferenceEquals(this.contentMeetingField, value) != true)) {
                    this.contentMeetingField = value;
                    this.RaisePropertyChanged("contentMeeting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.ServiceReference4.Course course {
            get {
                return this.courseField;
            }
            set {
                if ((object.ReferenceEquals(this.courseField, value) != true)) {
                    this.courseField = value;
                    this.RaisePropertyChanged("course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.ServiceReference4.Sceduel ddate {
            get {
                return this.ddateField;
            }
            set {
                if ((object.ReferenceEquals(this.ddateField, value) != true)) {
                    this.ddateField = value;
                    this.RaisePropertyChanged("ddate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isPerformed {
            get {
                return this.isPerformedField;
            }
            set {
                if ((this.isPerformedField.Equals(value) != true)) {
                    this.isPerformedField = value;
                    this.RaisePropertyChanged("isPerformed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int lengthSessionInminutes {
            get {
                return this.lengthSessionInminutesField;
            }
            set {
                if ((this.lengthSessionInminutesField.Equals(value) != true)) {
                    this.lengthSessionInminutesField = value;
                    this.RaisePropertyChanged("lengthSessionInminutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                if ((object.ReferenceEquals(this.notesField, value) != true)) {
                    this.notesField = value;
                    this.RaisePropertyChanged("notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int serial {
            get {
                return this.serialField;
            }
            set {
                if ((this.serialField.Equals(value) != true)) {
                    this.serialField = value;
                    this.RaisePropertyChanged("serial");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customers", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Customers : client.ServiceReference4.BaseEntity {
        
        private string adressField;
        
        private client.ServiceReference4.Cities cityField;
        
        private int codeField;
        
        private string mailField;
        
        private string nameField;
        
        private string notesField;
        
        private string telephoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adress {
            get {
                return this.adressField;
            }
            set {
                if ((object.ReferenceEquals(this.adressField, value) != true)) {
                    this.adressField = value;
                    this.RaisePropertyChanged("adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client.ServiceReference4.Cities city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                if ((object.ReferenceEquals(this.notesField, value) != true)) {
                    this.notesField = value;
                    this.RaisePropertyChanged("notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telephone {
            get {
                return this.telephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.telephoneField, value) != true)) {
                    this.telephoneField = value;
                    this.RaisePropertyChanged("telephone");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCustomers", ReplyAction="http://tempuri.org/IService1/AddCustomersResponse")]
        System.Threading.Tasks.Task<int> AddCustomersAsync(client.ServiceReference4.Customers c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSceduel", ReplyAction="http://tempuri.org/IService1/AddSceduelResponse")]
        System.Threading.Tasks.Task<int> AddSceduelAsync(client.ServiceReference4.Sceduel c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPersonalMeeting", ReplyAction="http://tempuri.org/IService1/AddPersonalMeetingResponse")]
        System.Threading.Tasks.Task<int> AddPersonalMeetingAsync(client.ServiceReference4.PersonalMeeting p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCourse", ReplyAction="http://tempuri.org/IService1/AddCourseResponse")]
        System.Threading.Tasks.Task<int> AddCourseAsync(client.ServiceReference4.Course c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCity", ReplyAction="http://tempuri.org/IService1/AddCityResponse")]
        System.Threading.Tasks.Task<int> AddCityAsync(client.ServiceReference4.Cities c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPersonToCourse", ReplyAction="http://tempuri.org/IService1/AddPersonToCourseResponse")]
        System.Threading.Tasks.Task<int> AddPersonToCourseAsync(client.ServiceReference4.RegistrationForCourse rf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCourseMeeting", ReplyAction="http://tempuri.org/IService1/AddCourseMeetingResponse")]
        System.Threading.Tasks.Task<int> AddCourseMeetingAsync(client.ServiceReference4.CourseMeeting cm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTypeCourse", ReplyAction="http://tempuri.org/IService1/AddTypeCourseResponse")]
        System.Threading.Tasks.Task<int> AddTypeCourseAsync(client.ServiceReference4.TypeCourse tc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTypeAdvice", ReplyAction="http://tempuri.org/IService1/AddTypeAdviceResponse")]
        System.Threading.Tasks.Task<int> AddTypeAdviceAsync(client.ServiceReference4.TypeAdvice ta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCustomers", ReplyAction="http://tempuri.org/IService1/UpdateCustomersResponse")]
        System.Threading.Tasks.Task<int> UpdateCustomersAsync(client.ServiceReference4.Customers c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateSceduel", ReplyAction="http://tempuri.org/IService1/UpdateSceduelResponse")]
        System.Threading.Tasks.Task<int> UpdateSceduelAsync(client.ServiceReference4.Sceduel c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePersonalMeeting", ReplyAction="http://tempuri.org/IService1/UpdatePersonalMeetingResponse")]
        System.Threading.Tasks.Task<int> UpdatePersonalMeetingAsync(client.ServiceReference4.PersonalMeeting p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCourse", ReplyAction="http://tempuri.org/IService1/UpdateCourseResponse")]
        System.Threading.Tasks.Task<int> UpdateCourseAsync(client.ServiceReference4.Course c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCities", ReplyAction="http://tempuri.org/IService1/UpdateCitiesResponse")]
        System.Threading.Tasks.Task<int> UpdateCitiesAsync(client.ServiceReference4.Cities c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCourseMeeting", ReplyAction="http://tempuri.org/IService1/UpdateCourseMeetingResponse")]
        System.Threading.Tasks.Task<int> UpdateCourseMeetingAsync(client.ServiceReference4.CourseMeeting cm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRegistrationToCourse", ReplyAction="http://tempuri.org/IService1/UpdateRegistrationToCourseResponse")]
        System.Threading.Tasks.Task<int> UpdateRegistrationToCourseAsync(client.ServiceReference4.RegistrationForCourse rc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTypeCurse", ReplyAction="http://tempuri.org/IService1/UpdateTypeCurseResponse")]
        System.Threading.Tasks.Task<int> UpdateTypeCurseAsync(client.ServiceReference4.TypeCourse tc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTypeAdvice", ReplyAction="http://tempuri.org/IService1/UpdateTypeAdviceResponse")]
        System.Threading.Tasks.Task<int> UpdateTypeAdviceAsync(client.ServiceReference4.TypeAdvice ta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCustomers", ReplyAction="http://tempuri.org/IService1/DeleteCustomersResponse")]
        System.Threading.Tasks.Task<int> DeleteCustomersAsync(client.ServiceReference4.Customers c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSceduel", ReplyAction="http://tempuri.org/IService1/DeleteSceduelResponse")]
        System.Threading.Tasks.Task<int> DeleteSceduelAsync(client.ServiceReference4.Sceduel c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePersonalMeeting", ReplyAction="http://tempuri.org/IService1/DeletePersonalMeetingResponse")]
        System.Threading.Tasks.Task<int> DeletePersonalMeetingAsync(client.ServiceReference4.PersonalMeeting p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCourse", ReplyAction="http://tempuri.org/IService1/DeleteCourseResponse")]
        System.Threading.Tasks.Task<int> DeleteCourseAsync(client.ServiceReference4.Course c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCity", ReplyAction="http://tempuri.org/IService1/DeleteCityResponse")]
        System.Threading.Tasks.Task<int> DeleteCityAsync(client.ServiceReference4.Cities c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRegistrationToCourse", ReplyAction="http://tempuri.org/IService1/DeleteRegistrationToCourseResponse")]
        System.Threading.Tasks.Task<int> DeleteRegistrationToCourseAsync(client.ServiceReference4.RegistrationForCourse rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteTypeCourse", ReplyAction="http://tempuri.org/IService1/DeleteTypeCourseResponse")]
        System.Threading.Tasks.Task<int> DeleteTypeCourseAsync(client.ServiceReference4.TypeCourse tc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteTypeAdvice", ReplyAction="http://tempuri.org/IService1/DeleteTypeAdviceResponse")]
        System.Threading.Tasks.Task<int> DeleteTypeAdviceAsync(client.ServiceReference4.TypeAdvice ta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCourseMeeting", ReplyAction="http://tempuri.org/IService1/DeleteCourseMeetingResponse")]
        System.Threading.Tasks.Task<int> DeleteCourseMeetingAsync(client.ServiceReference4.CourseMeeting cm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodeToCustomers", ReplyAction="http://tempuri.org/IService1/GetCodeToCustomersResponse")]
        System.Threading.Tasks.Task<int> GetCodeToCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodeToCourseMeeting", ReplyAction="http://tempuri.org/IService1/GetCodeToCourseMeetingResponse")]
        System.Threading.Tasks.Task<int> GetCodeToCourseMeetingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodeToSceduel", ReplyAction="http://tempuri.org/IService1/GetCodeToSceduelResponse")]
        System.Threading.Tasks.Task<int> GetCodeToSceduelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodeToPersonalMeeting", ReplyAction="http://tempuri.org/IService1/GetCodeToPersonalMeetingResponse")]
        System.Threading.Tasks.Task<int> GetCodeToPersonalMeetingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodeToCourse", ReplyAction="http://tempuri.org/IService1/GetCodeToCourseResponse")]
        System.Threading.Tasks.Task<int> GetCodeToCourseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodeToCity", ReplyAction="http://tempuri.org/IService1/GetCodeToCityResponse")]
        System.Threading.Tasks.Task<int> GetCodeToCityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodeToTypeCourse", ReplyAction="http://tempuri.org/IService1/GetCodeToTypeCourseResponse")]
        System.Threading.Tasks.Task<int> GetCodeToTypeCourseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCodeToTypeAdvice", ReplyAction="http://tempuri.org/IService1/GetCodeToTypeAdviceResponse")]
        System.Threading.Tasks.Task<int> GetCodeToTypeAdviceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPersonalMeetingList", ReplyAction="http://tempuri.org/IService1/GetPersonalMeetingListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.PersonalMeeting>> GetPersonalMeetingListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSceduelList", ReplyAction="http://tempuri.org/IService1/GetSceduelListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.Sceduel>> GetSceduelListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCourseList", ReplyAction="http://tempuri.org/IService1/GetCourseListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.Course>> GetCourseListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomersList", ReplyAction="http://tempuri.org/IService1/GetCustomersListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.Customers>> GetCustomersListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCitiesList", ReplyAction="http://tempuri.org/IService1/GetCitiesListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.Cities>> GetCitiesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRegistrationToCourseList", ReplyAction="http://tempuri.org/IService1/GetRegistrationToCourseListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.RegistrationForCourse>> GetRegistrationToCourseListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCourseMeetingList", ReplyAction="http://tempuri.org/IService1/GetCourseMeetingListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.CourseMeeting>> GetCourseMeetingListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTypeAdviceList", ReplyAction="http://tempuri.org/IService1/GetTypeAdviceListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.TypeAdvice>> GetTypeAdviceListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTypeCourseList", ReplyAction="http://tempuri.org/IService1/GetTypeCourseListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.TypeCourse>> GetTypeCourseListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddLstCourseMeeting", ReplyAction="http://tempuri.org/IService1/AddLstCourseMeetingResponse")]
        System.Threading.Tasks.Task<int> AddLstCourseMeetingAsync(int list, client.ServiceReference4.Course course);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : client.ServiceReference4.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<client.ServiceReference4.IService1>, client.ServiceReference4.IService1 {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<int> AddCustomersAsync(client.ServiceReference4.Customers c) {
            return base.Channel.AddCustomersAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> AddSceduelAsync(client.ServiceReference4.Sceduel c) {
            return base.Channel.AddSceduelAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> AddPersonalMeetingAsync(client.ServiceReference4.PersonalMeeting p) {
            return base.Channel.AddPersonalMeetingAsync(p);
        }
        
        public System.Threading.Tasks.Task<int> AddCourseAsync(client.ServiceReference4.Course c) {
            return base.Channel.AddCourseAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> AddCityAsync(client.ServiceReference4.Cities c) {
            return base.Channel.AddCityAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> AddPersonToCourseAsync(client.ServiceReference4.RegistrationForCourse rf) {
            return base.Channel.AddPersonToCourseAsync(rf);
        }
        
        public System.Threading.Tasks.Task<int> AddCourseMeetingAsync(client.ServiceReference4.CourseMeeting cm) {
            return base.Channel.AddCourseMeetingAsync(cm);
        }
        
        public System.Threading.Tasks.Task<int> AddTypeCourseAsync(client.ServiceReference4.TypeCourse tc) {
            return base.Channel.AddTypeCourseAsync(tc);
        }
        
        public System.Threading.Tasks.Task<int> AddTypeAdviceAsync(client.ServiceReference4.TypeAdvice ta) {
            return base.Channel.AddTypeAdviceAsync(ta);
        }
        
        public System.Threading.Tasks.Task<int> UpdateCustomersAsync(client.ServiceReference4.Customers c) {
            return base.Channel.UpdateCustomersAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> UpdateSceduelAsync(client.ServiceReference4.Sceduel c) {
            return base.Channel.UpdateSceduelAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePersonalMeetingAsync(client.ServiceReference4.PersonalMeeting p) {
            return base.Channel.UpdatePersonalMeetingAsync(p);
        }
        
        public System.Threading.Tasks.Task<int> UpdateCourseAsync(client.ServiceReference4.Course c) {
            return base.Channel.UpdateCourseAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> UpdateCitiesAsync(client.ServiceReference4.Cities c) {
            return base.Channel.UpdateCitiesAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> UpdateCourseMeetingAsync(client.ServiceReference4.CourseMeeting cm) {
            return base.Channel.UpdateCourseMeetingAsync(cm);
        }
        
        public System.Threading.Tasks.Task<int> UpdateRegistrationToCourseAsync(client.ServiceReference4.RegistrationForCourse rc) {
            return base.Channel.UpdateRegistrationToCourseAsync(rc);
        }
        
        public System.Threading.Tasks.Task<int> UpdateTypeCurseAsync(client.ServiceReference4.TypeCourse tc) {
            return base.Channel.UpdateTypeCurseAsync(tc);
        }
        
        public System.Threading.Tasks.Task<int> UpdateTypeAdviceAsync(client.ServiceReference4.TypeAdvice ta) {
            return base.Channel.UpdateTypeAdviceAsync(ta);
        }
        
        public System.Threading.Tasks.Task<int> DeleteCustomersAsync(client.ServiceReference4.Customers c) {
            return base.Channel.DeleteCustomersAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> DeleteSceduelAsync(client.ServiceReference4.Sceduel c) {
            return base.Channel.DeleteSceduelAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> DeletePersonalMeetingAsync(client.ServiceReference4.PersonalMeeting p) {
            return base.Channel.DeletePersonalMeetingAsync(p);
        }
        
        public System.Threading.Tasks.Task<int> DeleteCourseAsync(client.ServiceReference4.Course c) {
            return base.Channel.DeleteCourseAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> DeleteCityAsync(client.ServiceReference4.Cities c) {
            return base.Channel.DeleteCityAsync(c);
        }
        
        public System.Threading.Tasks.Task<int> DeleteRegistrationToCourseAsync(client.ServiceReference4.RegistrationForCourse rfc) {
            return base.Channel.DeleteRegistrationToCourseAsync(rfc);
        }
        
        public System.Threading.Tasks.Task<int> DeleteTypeCourseAsync(client.ServiceReference4.TypeCourse tc) {
            return base.Channel.DeleteTypeCourseAsync(tc);
        }
        
        public System.Threading.Tasks.Task<int> DeleteTypeAdviceAsync(client.ServiceReference4.TypeAdvice ta) {
            return base.Channel.DeleteTypeAdviceAsync(ta);
        }
        
        public System.Threading.Tasks.Task<int> DeleteCourseMeetingAsync(client.ServiceReference4.CourseMeeting cm) {
            return base.Channel.DeleteCourseMeetingAsync(cm);
        }
        
        public System.Threading.Tasks.Task<int> GetCodeToCustomersAsync() {
            return base.Channel.GetCodeToCustomersAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCodeToCourseMeetingAsync() {
            return base.Channel.GetCodeToCourseMeetingAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCodeToSceduelAsync() {
            return base.Channel.GetCodeToSceduelAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCodeToPersonalMeetingAsync() {
            return base.Channel.GetCodeToPersonalMeetingAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCodeToCourseAsync() {
            return base.Channel.GetCodeToCourseAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCodeToCityAsync() {
            return base.Channel.GetCodeToCityAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCodeToTypeCourseAsync() {
            return base.Channel.GetCodeToTypeCourseAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCodeToTypeAdviceAsync() {
            return base.Channel.GetCodeToTypeAdviceAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.PersonalMeeting>> GetPersonalMeetingListAsync() {
            return base.Channel.GetPersonalMeetingListAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.Sceduel>> GetSceduelListAsync() {
            return base.Channel.GetSceduelListAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.Course>> GetCourseListAsync() {
            return base.Channel.GetCourseListAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.Customers>> GetCustomersListAsync() {
            return base.Channel.GetCustomersListAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.Cities>> GetCitiesListAsync() {
            return base.Channel.GetCitiesListAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.RegistrationForCourse>> GetRegistrationToCourseListAsync() {
            return base.Channel.GetRegistrationToCourseListAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.CourseMeeting>> GetCourseMeetingListAsync() {
            return base.Channel.GetCourseMeetingListAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.TypeAdvice>> GetTypeAdviceListAsync() {
            return base.Channel.GetTypeAdviceListAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<client.ServiceReference4.TypeCourse>> GetTypeCourseListAsync() {
            return base.Channel.GetTypeCourseListAsync();
        }
        
        public System.Threading.Tasks.Task<int> AddLstCourseMeetingAsync(int list, client.ServiceReference4.Course course) {
            return base.Channel.AddLstCourseMeetingAsync(list, course);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WcfServer/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IService1,
        }
    }
}
